config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :users
  resources :events do
  	resources :attendances
  end
  root 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :attendee, class_name: "User"
	belongs_to :event
	after_create :notice_send

  def notice_send
    AdminMailer.new_attendee_email(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :attendees, class_name: "User", through: :attendances
  belongs_to :administrator, foreign_key: 'administrator_id', class_name: "User"
  validates :start_date, presence: true
  validate :start_date_must_be_in_the_future
  validates :duration, presence: true, numericality: {greater_than: 0, only_integer:true}
  validate :duration_is_multiple_of_five
  validates :title, presence: true, length: { in: 5..140}
  validates :description, presence: true, length: { in: 20..1000}
  validates :price, presence: true, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 1000, only_integer:true}
  validates :location, presence: true

   def start_date_must_be_in_the_future
    errors.add(:start_date, "must be before end time") unless start_date.present? && self.start_date.to_i > Time.now.to_i
  end

  def duration_is_multiple_of_five
    errors.add(:duration, "must be a multiple of 5") unless self.duration % 5 == 0
  end

  def self.end_date(id)
    self.find(id).start_date + (self.find(id).duration)*60
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :event_creations, foreign_key: 'administrator_id', class_name: "Event"
  has_many :event_attendances, foreign_key: 'attendee_id', class_name: "Attendance"
  has_many :events, through: :event_attendances
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
before_action :authenticate_administrator, only: [:index]
before_action :already_attendee_or_admin

  def index
  @event = Event.find(params[:event_id])
  @all_attendances = @event.attendances
  end

  def new
  @event = Event.find(params[:event_id])
  @attendance = Attendance.new
  end

  def create
    @event = Event.find(params[:event_id])
    @amount = @event.price*100

    customer = Stripe::Customer.create(
     :email => params[:stripeEmail],
     :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
    
    @attendance = Attendance.new(stripe_customer_id: charge[:customer], attendee: current_user, event: @event)

    if @attendance.save
      redirect_to root_path
    else
      flash[:danger] = "Il manque des informations !"
      render :new 
    end


  end

  def edit
  end

  def show
  end

private

  def authenticate_administrator
    @event = Event.find(params[:event_id])
    unless current_user == @event.administrator
      flash[:danger] = "Vous n'avez pas accès à cette fonctionnalité"
      redirect_to event_path(params[:event_id])
    end
  end

  def already_attendee_or_admin
    @event = Event.find(params[:event_id])
    if (current_user == @event.administrator) || (@event.attendees.include?(current_user))
      flash[:danger] = "Vous n'avez pas accès à cette fonctionnalité"
      redirect_to event_path(params[:event_id])
    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @event = Event.find(params[:event_id])
    puts "*"*50
    puts "je suis dans 'new'"
    puts "*"*50
    puts params
    puts "*"*5
    puts @amount
    puts "*"*50
  end

  def create
    @event = Event.find(params[:event_id])
    @amount = @event.price
    puts "*"*50
    puts "je suis dans 'create'"
    puts "*"*50
    puts params
    puts "*"*5
    puts @event
    puts "*"*50

   customer = Stripe::Customer.create(
     :email => params[:stripeEmail],
     :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
    
    puts "*"*50
    puts charge[:customer]
    puts "*"*50

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :authenticate_user!, only: [:new]

  def index
  	@all_events = Event.all
  end

  def show
  	@event = Event.find(params[:id])
    @event_end_date = Event.end_date(params[:id])
  end

  def new
  	@event = Event.new
  end

  def create
    @event = Event.new(title: params[:title], description: params[:description], price: params[:price].to_i, location: params[:location], administrator: current_user, start_date: (params[:hour] +" "+ params[:day]), duration: params[:duration])

  	if @event.save
  		redirect_to root_path
  	else
  	  flash[:danger] = "Il manque des informations !"
  	  render :new 
  	end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    post_params = params[:event]
    if @event.update(title: post_params[:title], description: post_params[:description], price: post_params[:price].to_i, location: post_params[:location], start_date: post_params[:start_date], duration: post_params[:duration])
      redirect_to event_path(params[:id])
    else
      flash[:danger] = "Il manque des informations !"
      render :new 
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    flash[:notice] = "Vous avez supprimé un potin avec succès !"
    redirect_to root_path
  end

private

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!, only: [:show, :edit]
before_action :verify_user_rights, only: [:show, :edit]
  
  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	post_params = params[:user]

  	if @user.update(first_name: post_params[:first_name], last_name: post_params[:last_name], description: post_params[:description])
  		redirect_to user_path(params[:id])
  	else
  	  flash[:danger] = "Il manque des informations !"
  	  render :new 
  	end
  end

private
  
  def verify_user_rights
  	unless current_user == User.find(params[:id])
  	flash[:danger] = "Vous ne pouvez pas faire ça !"
    redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/edit.html.erb
<h1>Attendances#edit</h1>
<p>Find me in app/views/attendances/edit.html.erb</p>

app/views/attendances/index.html.erb
<div class="jumbotron">
  <h1>Espace EVENT :  <%= @event.title %></h1>
  <h5 class="text-muted mb-3">Administrateur : <%= @event.administrator.first_name %><%= @event.administrator.last_name %></h5>
  <%= link_to "Editer l'EVENT", edit_event_path(@event.id), class: "btn-dark btn p-1" %>
</div>
<div>
Description : <%= @event.description %>
</div></br>

<div>
 Lieu : <%= @event.location %></br>
 Prix : <%= @event.price %>€</br> 
 Date : <%= @event.start_date.strftime("%H:%M") %> (<%= @event.start_date.strftime("%m/%d/%y") %>)</br>
 <% hours = @event.duration / 60 %>
 <% rest = @event.duration % 60 %>
 Durée : <%= hours %>h<%=rest%>
</div>

<p>Nombre de participants : <%=@all_attendances.count %> participants</p>

<h4>Voici la liste des participants à l'évènement</h4>

<% @all_attendances.each do |attendance| %>
<ul>
  <li>
 	<%= attendance.attendee.first_name %><%= attendance.attendee.last_name %></br>
	<%= attendance.attendee.email %></br>
    <%= attendance.created_at.strftime("%H:%M %m/%d/%y") %>
  </li>
</ul>	
<% end %>

app/views/attendances/new.html.erb
<%= form_tag url_for(action: 'create') do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: €<%= @event.price %>.00 </span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Inscription : <%= @event.title %>"
          data-amount= @event.price
          data-locale="auto"></script>
<% end %>

app/views/attendances/show.html.erb
<h1>Attendances#show</h1>
<p>Find me in app/views/attendances/show.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag event_charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: €<%= @event.price %>.00 </span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Inscription : <%= @event.title %>"
          data-amount= @event.price
          data-locale="auto"></script>
<% end %>

app/views/events/edit.html.erb
<% if @event.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Event update process failed due to:</p>
      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="header mt-4 mb-2">
  <h2> Que veux-tu changer ?</h2>
</div>

<%= form_for @event do |f| %>
  <div class="form-group">
    <h6 class=text-info>Titre</h6>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Ex: Fête de Pâques'%></br>
    <h6 class=text-info>Description de l'évènement</h6>
    <%= f.text_field :description, class: 'form-control', placeholder: 'Ex: Venez chasser les oeufs à la Félicita le dernier week-end de mars'%>
    <p class="small">Doit être compris entre 20 et 1000 caractères.</p></br>
    <h6 class=text-info>Prix</h6>
    <%= f.text_area :price, class: 'form-control', placeholder: 'Ex: 15'%>
    <p class="small">Doit être un chiffre entier positif.</p></br>
    <h6 class=text-info>Lieu</h6>
    <%= f.text_field :location, class: 'form-control', placeholder: 'Ex: La Félicita'%></br>
    <h6 class=text-info>Date</h6>
    <%= f.text_field :start_date, class: 'form-control', placeholder: 'Ex: 18h30 26/03/2019'%></br> 
    <h6 class=text-info>Durée</h6>
    <%= f.text_area :duration, class: 'form-control', placeholder: 'Ex: 120 (pour 2h)'%>
    <p class="small">Uniquement tranches horaires de 5 minutes comptabilisées (5min, 20min, 145min...)</p></br>       
  </div>
  <div class="form-group">
  <button type="submit" class="btn btn-secondary"> Enregistrer </button>
  </div>
<% end %>

<%= link_to "Supprimer EVENT", event_path(@event.id), method: "delete", class: "btn btn-danger", data: { confirm: "Vous-êtes vraiment sur ?"}%>

app/views/events/index.html.erb
<div class="jumbotron">
<% if user_signed_in?%>
  <h1 class="display-3 mb-5">Bienvenue</h1>
  <% if current_user.first_name == nil || current_user.last_name == nil ||  current_user.description == nil %>
    <p><%= link_to "Mets à jour ton profil !!!", user_path(current_user.id), class: "btn-info btn p-1" %></p>
  <% else %>
    <h1 class="display-3 mb-5">Bienvenue, <%= current_user.first_name %></h1>
    <p><%= link_to "Créer un nouvelle EVENT", new_event_path, class: "btn-info btn p-1" %></p>
  <% end %>
<% else %>
  <h2>Bienvenue, connecte-toi !!</h2>
<% end %>
</div>

<div class="mt-4">
  <% @all_events.each_with_index do |event, i| %>
    <div class="card mb-3" style="width: auto">
      <div class="card-body">
        <h5 class="card-title text-info"><%= event.title %></h5>
        <h6 class="card-subtitle mb-2 text-muted">Event n°<%= i+1 %></h6>
        <p class="card-text"><%= event.description %></p>
        <%= link_to "En savoir plus >>", event_path(event.id), class: "btn btn-info p-1" %>
      </div>
      <div class="card-footer text-muted">
        Date : 
        <%= event.start_date.strftime("%m/%d/%y") %>,
        <%= event.start_date.strftime("%kh%M") %></br>
        Lieu :
        <%= event.location %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<% if @event.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Event creation process failed due to:</p>
      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_tag url_for(action: 'create'), method: "post" do %>
  <h6 class=text-info>Titre</h6>
  <%= text_field_tag 'title', '', class: 'form-control', placeholder: 'Ex: Fête de Pâques'%>
  <p class="small">Doit être compris entre 5 et 140 caractères.</p></br>
  <h6 class=text-info>Prix</h6>
  <%= text_field_tag 'price', '', class: 'form-control', placeholder: 'Ex: 15'%>
  <p class="small">Doit être un chiffre entier positif.</p></br>
  <h6 class=text-info>Lieu</h6>
  <%= text_field_tag 'location', '', class: 'form-control', placeholder: 'Ex: La Félicita'%></br>
  <h6 class=text-info>Date</h6>
  <%= text_field_tag 'day', '', class: 'form-control', placeholder: 'Ex: 26/03/2019'%>
  </br>
  <h6 class=text-info>Horaire</h6>
  <%= text_field_tag 'hour', '', class: 'form-control', placeholder: 'Ex: 18:30'%></br>
  <h6 class=text-info>Durée</h6>
  <%= text_field_tag 'duration', '', class: 'form-control', placeholder: 'Ex: 120 (pour 2h)'%>
  <p class="small">Uniquement tranches horaires de 5 minutes comptabilisées (5min, 20min, 145min...)</p></br>
  <h6 class=text-info>Description</h6>
  <%= text_area_tag 'description', '', class: 'form-control', placeholder: 'Ex: Venez chasser les oeufs à la Félicita le dernier week-end de mars'%>
  <p class="small">Doit être compris entre 20 et 1000 caractères.</p></br>

  <%= submit_tag "Créer l'Event", class: "btn btn-info" %></br>
<% end %>
<p></p>

app/views/events/show.html.erb
 <h1> <%= @event.title %> </h1>
 <p>
 Description : </br>
 	<%= @event.description %>
 </p>

 <p>
 Où ? <%= @event.location %></br>
 Début ? <%= @event.start_date.strftime("%H:%M") %> (<%= @event.start_date.strftime("%m/%d/%y") %>)</br>
 Fin ? <%= @event_end_date.strftime("%H:%M") %> (<%= @event_end_date.strftime("%m/%d/%y") %>)</br>
 Et le prix ? <%= @event.price %>€</br> 
 <% hours = @event.duration / 60 %>
 <% rest = @event.duration % 60 %>
 Durée ? <%= hours %>h<%=rest%>
</p>

<p>
  Contacter le créateur de l'évènement : <%=@event.administrator.email %>
</p>

<p>
  Nombre de participants : <%=@event.attendances.count %> participants
</p>


<p>
  <% if (current_user == @event.administrator) || (@event.attendees.include?(current_user)) %>
  Vous participez à cet évènement !
  <%else%>
  <%= link_to "Participer", new_event_attendance_path(params[:id]), class: "btn-dark btn p-1" %>
  <% end %>
</p>
<p>
  <% if current_user == @event.administrator %>
  <%= link_to "Mon espace EVENT", event_attendances_path(params[:id]), class: "btn-dark btn p-1" %>
  <% end %>
</p>

app/views/home/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>
    <li>
      Voici ton email : <%= current_user.email %>
    </li>
    <li>
      <%= link_to "Secret page", home_secret_path %>
    </li>
    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>
  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>
    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/home/secret.html.erb
<h1>Home#secret</h1>
<p>Find me in app/views/home/secret.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "EventLike", events_path, class: "navbar-brand"%>
      <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Créer un EVENT", new_event_path, class: "nav-item nav-link"%>
        </div>

        <div class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
          
          
            <div class="btn-group">
              <button type="button" class="btn btn-dark"><%= current_user.first_name %></button>
              <button type="button" class="btn btn-dark dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Toggle Dropdown</span>
              </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <%= link_to "Mon profil", user_path(current_user.id), class: "dropdown-item" %>
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item", data: { confirm: "Quitter définitivement ?"}  %>
                </div>
            </div>
  
          <%else%>

          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

        <div class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
          
          <div class="btn-group">
              <button type="button" class="btn btn-dark">Connection</button>
              <button type="button" class="btn btn-dark dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="sr-only">Menu déroulant</span>
              </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                <%= link_to "Sign in", new_user_session_path, class: "dropdown-item" %>
                <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
                </div>
            </div>
          <%end%>

        </div>  
        </div>
      </div>
    </nav>
<% if flash[:danger] %>
  <div class="alert alert-danger" role="alert">
   <div class="notice"> 
     <%=flash[:danger] %> 
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
     </button>
   </div>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
   <div class="notice"> 
     <%=flash[:notice] %> 
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
     </button>
   </div>
  </div>
<% end %>
    <div class="container-fluid">
    <%= yield %>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>User update process failed due to:</p>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="header mt-4 mb-2">
  <h2> Parle-nous de toi...</h2>
</div>

<%= form_for @user do |f| %>
  <div class="form-group">
    <h6 class=text-info>Prénom</h6>
    <%= f.text_field :first_name, class: 'form-control', placeholder: 'Prénom'%></br>
    <h6 class=text-info>Nom</h6>
    <%= f.text_field :last_name, class: 'form-control', placeholder: 'Nom'%></br>
    <h6 class=text-info>Parle-nous de toi!</h6>
    <%= f.text_area :description, class: 'form-control', placeholder: 'Description'%></br>
  </div>
  <div class="form-group">
  <button type="submit" class="btn btn-secondary"> Enregistrer </button>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<% if current_user.first_name == nil || current_user.last_name == nil ||  current_user.description == nil %>
</br><%= link_to "Compléter mon profil EventLike", edit_user_path, class: "btn-dark btn p-1" %>

<% else %>

<h1 class="mt-4">Espace de <%= @user.first_name %> <%= @user.last_name %></h1>
<p>
	<ul>
		<li> Prénom : <%= @user.first_name %></li>
		<li> Nom : <%= @user.last_name %></li>
		<li> Description : <%= @user.description %></li>
		<li> Email : <%= @user.email %></li>
	</ul>
</p>

<p>
	<%= link_to "Editer password / email", edit_user_registration_path, class: "btn-dark btn p-1" %>
	<%= link_to "Editer autres informations", edit_user_path, class: "btn-dark btn p-1" %>
</p>

<h3 class="mt-5">Evènements crées</h3>
<p>
<div class="row mt-4">	
  <% @user.events.each_with_index do |event, i| %>
  <div class="card mx-2 mb-3" style="width: 15rem">
	<div class="card-body">
	  <h5 class="card-title text-info"><%= event.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted">Event n°<%= i+1 %></h6>	
      <p class="card-text text-muted"><%= event.start_date.strftime("%m/%d/%y") %></p>
	  <%= link_to "Page de l'Event", event_path(event.id), class: "btn-dark btn p-1" %>
	</div>
  </div>
  <% end %>
</div>
</p>

<% end %>